name: C++ CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t line-follower-dev .

      - name: Verify Executable
        run: docker run --rm line-follower-dev ls -l controllers/EPuckLineFollowerOOP/EPuckLineFollowerOOP

      - name: Run Performance Analysis inside Docker
        # On lance python à l'intérieur du conteneur
        run: docker run --rm line-follower-dev python3 analysis/generate_report.py